__version__ = '0.6.2-rc.7'
__author__ = 'David LePage'
__description__ = 'Python based API to Stonesoft Security Management Center'
__url__ = 'http://github.com/gabstopper/smc-python'
__author_email__ = 'dwlepage70@gmail.com'
__license__ = 'Apache 2.0'